title: Sportello Psicologico
owner: Dott.sse Ierace e Papini
description: Sportello Psicologico - Dott.sse Ierace e Papini

#url: http://brianmaierjr.github.com/long-haul
baseurl: ""
#paginate_path: "blog/page:num/"
#permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Chi siamo?
   url: /chi-siamo
 - title: Sostegno Psicologico
   url: /sostegno-psicologico
 - title: Terapia Individuale
   url: /terapia-individuale
 - title: Terapia di Coppia
   url: /terapia-di-coppia
 - title: Terapia Familiare
   url: /terapia-familiare
 - title: Contattaci
   url: /contattaci

social:
#   github: brianmaierjr
#   twitter: brianmaierjr
#   facebook: brianmaierjr
   email: elenaierace@gmail.com

#google_analytics: "UA-58263416-1"
