title: Sportello Psicologico
description: Sportello Psicologico - Dott.sse Ierace e Papini

#url: http://brianmaierjr.github.com/long-haul
baseurl: ""
#paginate_path: "blog/page:num/"
#permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Chi siamo?
   url: /about
 - title: Sostegno Psicologico
 - title: Terapia Individuale
 - title: Terapia di Coppia
 - title: Terapia Familiare
 - title: Contatti
   url: /contact

social:
#   github: brianmaierjr
#   twitter: brianmaierjr
#   facebook: brianmaierjr
   email: elenaierace@gmail.com

#google_analytics: "UA-58263416-1"
